### ISSUE TITLE
Craftable Recipe Missing

### ISSUE THREAD

**Issue by kevpears** [Adirelle/AdiCrafter#2]
Hello,

Upon attempt to using this mod, I had found that there is not an existing recipe to craft your block. I can see that it exists when I use creative mode, but there is not an actual way to craft the block. Your notes on the main page also do not provide this information.

Thanks,
kevpears

**Comment by Adirelle** [comment]
Yes, I am sorry. Actually the recipe is there but is not documented. I am so used to REI that I forgot that some people does not use it. I will add some information in the notes.

**Comment by kevpears** [comment]
Thanks for the fast updates, I use REI as well. I'm assuming since I had it installed locally it was showing the block but on the server it just wasn't posting the recipe. With your update, it appears everything is loaded well with no issues. Thank you for the updates!
